name: Release WinMediaPie

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]
        release-platform: ["x86", "x64"]

    steps:
      - name: Extract tag name
        uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore NuGet packages
        run: msbuild -t:restore

      - name: Build for platform ${{ matrix.release-platform }}
        run: msbuild WinMediaPie.csproj /p:Configuration=Release /p:Platform=${{ matrix.release-platform }}

      - name: ZIP build artifacts
        uses: papeloto/action-zip@v1
        with:
          files: bin/${{matrix.release-platform}}/Release/
          recursive: true
          dest: WinMediaPie-${{ steps.tagName.outputs.tag }}-${{ matrix.release-platform }}.zip

  publish:
    runs-on: windows-latest
    needs: [build]
    steps:
      - name: Release ${{ steps.tagName.outputs.tag }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          title: ${{ steps.tagName.outputs.tag }}
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            WinMediaPie-${{ steps.tagName.outputs.tag }}-*.zip
        env:
          CI: true
